[workspace]
members = [
    "crates/pfg-model",
    "crates/pfg-policy",
    "crates/pfg-format-image",
    "crates/pfg-format-pdf",
    "crates/pfg-format-office",
    "crates/pfg-core",
    "crates/pfg-cli",
    "crates/pfg-desktop",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

